trigger:
- master
pr:
  branches:
    include: ['*']

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'
- script: |
      docker run thiagobarradas/magento2:2.2.0-php7.0 