# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
- main

pool:
  vmImage: 'ubuntu-16.04'
  container:
      image: php:7.2-apache
      options: --privileged

variables:
- group: control-media
- name: phpVersion
  value: 7.2

stages:
- stage: BuildApp
  jobs:   
  - job: CheckVersion
    steps: 
    - script: |
        sudo update-alternatives --set php /usr/bin/php$(phpVersion)
        sudo update-alternatives --set phar /usr/bin/phar$(phpVersion)
        sudo update-alternatives --set phpdbg /usr/bin/phpdbg$(phpVersion)
        sudo update-alternatives --set php-cgi /usr/bin/php-cgi$(phpVersion)
        sudo update-alternatives --set phar.phar /usr/bin/phar.phar$(phpVersion)
        php -version
         ls -la '$(System.DefaultWorkingDirectory)/control-media-backend'            
      displayName: 'Use PHP version $(phpVersion)'   
    - bash: env
      displayName: Show environment variables

  - job: Build
    dependsOn: 
    - CheckVersion
    condition: succeeded()
    steps:   
    - script: |     
        sudo update-alternatives --set php /usr/bin/php$(phpVersion)
        sudo update-alternatives --set phar /usr/bin/phar$(phpVersion)
        sudo update-alternatives --set phpdbg /usr/bin/phpdbg$(phpVersion)
        sudo update-alternatives --set php-cgi /usr/bin/php-cgi$(phpVersion)
        sudo update-alternatives --set phar.phar /usr/bin/phar.phar$(phpVersion)
        php -version 
        sudo composer self-update --1       
        composer        
        cd control-media-backend && composer install --no-interaction --prefer-dist
        ls -la '$(System.DefaultWorkingDirectory)/control-media-backend/vendor'
      displayName: Build Application
    - task: PublishPipelineArtifact@1
      displayName: Store Application Artifact0
      inputs:
        path: '$(System.DefaultWorkingDirectory)/control-media-backend/vendor'
        artifact: vendor

  - job: UnitTests
    dependsOn: 
    - Build
    condition: succeeded()
    steps: 
    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: vendor
    - script: |
        ls $(Pipeline.Workspace)
        sudo update-alternatives --set php /usr/bin/php$(phpVersion)
        sudo update-alternatives --set phar /usr/bin/phar$(phpVersion)
        sudo update-alternatives --set phpdbg /usr/bin/phpdbg$(phpVersion)
        sudo update-alternatives --set php-cgi /usr/bin/php-cgi$(phpVersion)
        sudo update-alternatives --set phar.phar /usr/bin/phar.phar$(phpVersion)
        php -version          
    - script: |   
        ls $(Pipeline.Workspace) 
        cp -a $(Pipeline.Workspace) control-media-backend/vendor/       
        mv $(Pipeline.Workspace)/vendor control-media-backend/vendor/         
        ls -la
        control-media-backend/vendor/bin/phpunit --coverage-clover $(System.DefaultWorkingDirectory)/artifact/clover.xml
      displayName: Build Applicathion
    - task: PublishPipelineArtifact@1
      displayName: Store Application Artifact
      inputs:
        path: $(System.DefaultWorkingDirectory)/artifact
        artifact: $(main_project_name)
    - script: |
        pwd && ls -la
        ls $(main_project_name)
        ls (System.DefaultWorkingDirectory)        
      
