trigger:
- master
pr:
  branches:
    include: ['*']

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'
- script: |
      docker run --name newimage -d -p3306:3306 -p80:80 thiagobarradas/magento2:2.2.0-php7.0 
      docker exec -i newimage sh -c "ls"
      docker exec -i newimage sh -c "ls /app"
      docker exec -i newimage sh -c "while ! /etc/init.d/mysql status | grep -m1 'is running'; do sleep 1; echo 'Waiting for mysql service...';  done; "
      docker exec -i newimage mysql magento2 -e \
            "INSERT INTO magento2.core_config_data VALUES (null, 'default', 0, 'customer/create_account/vat_frontend_visibility', 1);"
