# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
- main

pool:
  vmImage: 'ubuntu-16.04'
  container:
      image: php:7.2-apache
      options: --privileged

variables:
- group: control-media
- name: phpVersion
  value: 7.2

stages:
- stage: BuildApp
  jobs:    
  - job: Build
    steps:   
    - script: |     
        sudo update-alternatives --set php /usr/bin/php$(phpVersion)
        sudo update-alternatives --set phar /usr/bin/phar$(phpVersion)
        sudo update-alternatives --set phpdbg /usr/bin/phpdbg$(phpVersion)
        sudo update-alternatives --set php-cgi /usr/bin/php-cgi$(phpVersion)
        sudo update-alternatives --set phar.phar /usr/bin/phar.phar$(phpVersion)
        sudo apt-get install php-xdebug
        php -version
        sudo composer self-update --1
        composer
        cd control-media-backend && composer install --no-interaction --prefer-dist
        ls -la '$(System.DefaultWorkingDirectory)/control-media-backend/vendor'
        export XDEBUG_MODE=coverage
        vendor/bin/phpunit --coverage-clover $(System.DefaultWorkingDirectory)/artifact/clover.xml
      displayName: Build Application and run Unit Tests
    - task: PublishPipelineArtifact@1
      displayName: Store Application Artifact0
      inputs:
        path: '$(System.DefaultWorkingDirectory)/artifact'
        artifact: artifact

  - job: SonarCloud
    dependsOn: 
    - Build
    condition: succeeded()
    steps: 
    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: artifact
    - script: |
        ls $(Pipeline.Workspace)           
      
