version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_pw_shh
      MYSQL_DATABASE: test_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "9906:3306"
  composer:
    image: composer
    volumes:
      - ./:/project
    working_dir: /project
    stdin_open: true
    tty: true
    command: composer install
  php:
    build: "./php"
    container_name: php_web
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/
    ports:
      - "8100:8100"
    working_dir: /var/www/html
